// ─── Client-side demo data — works without Supabase
// Used by the dashboard seed button when no DB is configured.

import { ClaimObject } from '@/types/claim';

const NOW = new Date();
const mins = (n: number) => new Date(NOW.getTime() - n * 60000).toISOString();

export const DEMO_APPROVED: ClaimObject = {
  id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
  created_at: mins(12),
  updated_at: mins(2),
  user: {
    id: 'user-001',
    name: 'Sarah Chen',
    email: 'sarah.chen@email.com',
    policy_number: 'POL-88821047',
    insurer: 'Nationwide',
  },
  incident: {
    description: 'I was driving southbound on Route 9 when the vehicle in front braked suddenly. My front bumper made contact with their rear. We\'ve exchanged information. Airbags did not deploy.',
    location: { lat: 40.7128, lng: -74.006, address: '47 Route 9 South, Woodbridge, NJ 07095', city: 'Woodbridge', country: 'US' },
    timestamp: mins(15),
    vehicles_involved: ['2021 Honda Accord', '2019 Toyota Camry'],
    incident_type: 'vehicle_collision',
  },
  voice: {
    recording_url: '',
    enhanced_audio_url: '',
    transcript: 'I was driving southbound on Route 9 when the vehicle in front braked suddenly without warning. I was unable to stop in time and my front bumper made contact with their rear bumper. We have both pulled over safely. My airbags did not deploy. The other driver and I have exchanged insurance information.',
    stress_score: 0.61,
    acoustic_sentiment: 'stressed',
    duration_seconds: 24,
    audio_quality_score: 0.94,
  },
  photos: { urls: [], count: 4, captured_at: mins(12) },
  damage_analysis: {
    damage_location: 'front bumper, hood, grille assembly',
    severity: 'moderate',
    estimated_repair_cost: { min: 2400, max: 4200, currency: 'USD' },
    damage_consistent_with_description: true,
    damage_details: [
      'Front bumper cover cracked along lower edge — approximately 60cm split',
      'Hood panel shows impact crease consistent with frontal collision',
      'Grille assembly partially displaced, mounting clips fractured',
      'No structural frame damage visible in submitted photos',
      'Headlight assemblies appear intact with no lens fracture',
    ],
    affected_parts: ['front bumper cover', 'hood panel', 'grille assembly', 'upper radiator support'],
    gemini_raw: '{}',
  },
  environmental: {
    weather_condition: 'clear',
    temperature_celsius: 14,
    visibility: 'Good (> 1km)',
    precipitation: 'None',
    wind_speed_kmh: 18,
    road_conditions: 'Dry / Normal',
    contributing_factors: ['No adverse conditions identified'],
    data_timestamp: mins(10),
  },
  market_data: {
    average_repair_cost_usd: 3100,
    cost_range: { min: 2100, max: 4400 },
    market_location: 'Woodbridge, NJ',
    data_sources: ['repairsmith.com', 'cargurus.com'],
    retrieved_at: mins(10),
  },
  fraud_assessment: {
    confidence_score: 87,
    fraud_risk: 'low',
    reasoning: [
      'Damage pattern is geometrically consistent with described rear-end collision mechanics',
      'Claimant stress score (0.61) aligns with genuine post-accident emotional state',
      'Estimated repair cost falls within market range for Woodbridge, NJ auto body shops',
      'No prior claims filed under this policy number in the last 24 months',
      'Environmental conditions (dry road, good visibility) are consistent with sudden braking scenario',
      'Vehicle age and value ratio supports claim plausibility',
    ],
    model_version: '2.4.1',
    claims_trained_on: 847293,
    processing_time_ms: 1840,
    flags: [],
  },
  status: 'approved',
  processing_steps: {
    audio_received: true, audio_enhanced: true, transcript_ready: true,
    photos_analyzed: true, weather_fetched: true, pricing_fetched: true,
    fraud_scored: true, report_delivered: true,
  },
  resolution: {
    decision: 'approved',
    decided_at: mins(2),
    resolution_time_seconds: 142,
    fnol_delivered: true,
    fnol_delivered_at: mins(2),
    entire_task_id: null,
    entire_task_url: null,
    adjuster_notes: null,
  },
};

export const DEMO_ESCALATED: ClaimObject = {
  id: 'b2c3d4e5-f6a7-8901-bcde-f01234567891',
  created_at: mins(8),
  updated_at: mins(1),
  user: {
    id: 'user-002',
    name: 'Marcus Williams',
    email: 'marcus.w@email.com',
    policy_number: 'POL-44102983',
    insurer: 'Progressive',
  },
  incident: {
    description: 'Vehicle was parked outside my residence overnight. Woke up to find significant damage to the passenger side doors. No witnesses. No CCTV in the area.',
    location: { lat: 40.6892, lng: -74.0445, address: '221 Bay Street, Staten Island, NY 10301', city: 'Staten Island', country: 'US' },
    timestamp: mins(480),
    vehicles_involved: ['2022 BMW 5 Series'],
    incident_type: 'parked_vehicle_damage',
  },
  voice: {
    recording_url: '',
    enhanced_audio_url: '',
    transcript: 'Vehicle was parked outside my residence overnight. Woke up to find significant damage to the passenger side doors. No witnesses. No CCTV in the area.',
    stress_score: 0.19,
    acoustic_sentiment: 'calm',
    duration_seconds: 14,
    audio_quality_score: 0.89,
  },
  photos: { urls: [], count: 2, captured_at: mins(8) },
  damage_analysis: {
    damage_location: 'passenger side doors, quarter panel',
    severity: 'severe',
    estimated_repair_cost: { min: 6800, max: 11200, currency: 'USD' },
    damage_consistent_with_description: false,
    damage_details: [
      'Door panel damage shows linear scoring inconsistent with typical parking impact',
      'Impact pattern suggests sustained directional force rather than single collision event',
      'Quarter panel deformation extends beyond typical hit-and-run damage profile',
      'Photo metadata shows images captured 6 hours after claimed discovery time',
    ],
    affected_parts: ['front passenger door', 'rear passenger door', 'quarter panel', 'rocker panel'],
    gemini_raw: '{}',
  },
  environmental: {
    weather_condition: 'clear',
    temperature_celsius: 9,
    visibility: 'Good (> 1km)',
    precipitation: 'None',
    wind_speed_kmh: 8,
    road_conditions: 'Dry / Normal',
    contributing_factors: ['No adverse conditions identified'],
    data_timestamp: mins(6),
  },
  market_data: {
    average_repair_cost_usd: 7400,
    cost_range: { min: 5200, max: 12000 },
    market_location: 'Staten Island, NY',
    data_sources: ['repairsmith.com'],
    retrieved_at: mins(6),
  },
  fraud_assessment: {
    confidence_score: 54,
    fraud_risk: 'high',
    reasoning: [
      'Stress score (0.19) is anomalously low for a claimant reporting significant vehicle damage',
      'Damage pattern identified by Gemini is geometrically inconsistent with hit-and-run mechanics',
      'Photo metadata timestamp does not align with reported discovery time — 6-hour discrepancy detected',
      'Claim value ($6,800–$11,200) is in the 94th percentile for this policy tier',
      'No corroborating evidence — no witnesses, no CCTV, no other vehicle identified',
    ],
    model_version: '2.4.1',
    claims_trained_on: 847293,
    processing_time_ms: 2210,
    flags: ['LOW_STRESS_ANOMALY', 'DAMAGE_INCONSISTENCY', 'METADATA_MISMATCH', 'HIGH_VALUE_OUTLIER'],
  },
  status: 'escalated',
  processing_steps: {
    audio_received: true, audio_enhanced: true, transcript_ready: true,
    photos_analyzed: true, weather_fetched: true, pricing_fetched: true,
    fraud_scored: true, report_delivered: false,
  },
  resolution: {
    decision: 'escalated',
    decided_at: mins(1),
    resolution_time_seconds: 186,
    fnol_delivered: false,
    fnol_delivered_at: null,
    entire_task_id: 'GH-42',
    entire_task_url: 'https://github.com/oracle-demo/escalations/issues/42',
    adjuster_notes: null,
  },
};

export const DEMO_PROCESSING: ClaimObject = {
  id: 'c3d4e5f6-a7b8-9012-cdef-012345678902',
  created_at: mins(1),
  updated_at: mins(0),
  user: {
    id: 'user-003',
    name: 'Priya Kapoor',
    email: 'priya.k@email.com',
    policy_number: 'POL-77345621',
    insurer: 'Allstate',
  },
  incident: {
    description: 'Side-swipe collision on the highway. Other vehicle did not stop.',
    location: { lat: 40.7589, lng: -73.9851, address: 'I-95 North, Exit 14, New Jersey', city: 'Fort Lee', country: 'US' },
    timestamp: mins(2),
    vehicles_involved: ['2020 Tesla Model 3'],
    incident_type: 'vehicle_collision',
  },
  voice: null,
  photos: { urls: [], count: 3, captured_at: mins(1) },
  damage_analysis: null,
  environmental: null,
  market_data: null,
  fraud_assessment: null,
  status: 'analyzing',
  processing_steps: {
    audio_received: true, audio_enhanced: true, transcript_ready: true,
    photos_analyzed: false, weather_fetched: false, pricing_fetched: false,
    fraud_scored: false, report_delivered: false,
  },
  resolution: null,
};
