import { NextRequest, NextResponse } from 'next/server';
import { supabase } from '@/lib/supabase';
import { generateFnolPdf } from '@/lib/pdf/generate-fnol-pdf';
import { getResend } from '@/lib/integrations/resend';
import { ClaimObject } from '@/types/claim';

export async function POST(req: NextRequest) {
  try {
    const { claimId, signatureDataUrl } = await req.json();
    if (!claimId) return NextResponse.json({ error: 'claimId required' }, { status: 400 });

    // 1. Fetch full claim
    const { data, error } = await supabase.from('claims').select('*').eq('id', claimId).single();
    if (error || !data) return NextResponse.json({ error: 'Claim not found' }, { status: 404 });
    const claim = data as ClaimObject;

    // 2. Save signature to claim
    if (signatureDataUrl) {
      await supabase.from('claims').update({ signature_data_url: signatureDataUrl }).eq('id', claimId);
    }

    // 3. Generate PDF
    const pdfBytes = await generateFnolPdf(claim, signatureDataUrl ?? null);
    const pdfBuffer = Buffer.from(pdfBytes);
    const filename = `fnol-${claimId.substring(0, 8)}.pdf`;

    // 4. Upload to Supabase Storage (best-effort)
    let pdfUrl: string | null = null;
    try {
      const { data: uploadData } = await supabase.storage
        .from('fnol-pdfs')
        .upload(filename, pdfBuffer, { contentType: 'application/pdf', upsert: true });
      if (uploadData?.path) {
        const { data: publicUrl } = supabase.storage.from('fnol-pdfs').getPublicUrl(uploadData.path);
        pdfUrl = publicUrl?.publicUrl ?? null;
      }
    } catch (storageErr) {
      console.warn('Storage upload failed (non-fatal):', storageErr);
    }

    // 5. Send email via Resend
    const resend = getResend();
    const claimRef = claimId.substring(0, 8).toUpperCase();
    const incidentDesc = claim.incident?.description ?? 'Motor vehicle incident';

    await resend.emails.send({
      from: 'ORACLE Claims <onboarding@resend.dev>',
      to: 'malek.korashi@gmail.com',
      subject: `FNOL Submission — Claim ${claimRef}`,
      html: `
        <div style="font-family:sans-serif;max-width:600px;margin:0 auto">
          <h2 style="color:#0060bf">First Notice of Loss — ${claimRef}</h2>
          <p>A new FNOL has been submitted via ORACLE Claims.</p>
          <table style="width:100%;border-collapse:collapse;margin:16px 0">
            <tr><td style="padding:6px;font-weight:bold;color:#555">Claimant</td><td style="padding:6px">${claim.user?.name ?? '—'}</td></tr>
            <tr><td style="padding:6px;font-weight:bold;color:#555">Policy</td><td style="padding:6px">${claim.user?.policy_number ?? '—'}</td></tr>
            <tr><td style="padding:6px;font-weight:bold;color:#555">Insurer</td><td style="padding:6px">${claim.user?.insurer ?? '—'}</td></tr>
            <tr><td style="padding:6px;font-weight:bold;color:#555">Incident</td><td style="padding:6px">${incidentDesc}</td></tr>
            <tr><td style="padding:6px;font-weight:bold;color:#555">Submitted</td><td style="padding:6px">${new Date().toLocaleDateString('en-GB')}</td></tr>
          </table>
          <p>The completed FNOL form is attached to this email.</p>
          ${pdfUrl ? `<p><a href="${pdfUrl}">View PDF online</a></p>` : ''}
          <hr style="border:none;border-top:1px solid #eee;margin:24px 0">
          <p style="font-size:12px;color:#999">Generated by ORACLE Claims Platform</p>
        </div>
      `,
      attachments: [
        {
          filename,
          content: pdfBuffer,
        },
      ],
    });

    // 6. Update claim status
    await supabase.from('claims').update({
      fnol_submitted: true,
      fnol_pdf_url: pdfUrl,
    }).eq('id', claimId);

    return NextResponse.json({ success: true, pdfUrl });
  } catch (err) {
    console.error('fnol/submit error:', err);
    return NextResponse.json({ error: String(err) }, { status: 500 });
  }
}
